<?php

namespace Tests\Unit;

use App\Episodio;
use App\Temporada;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class TemporadaTest extends TestCase
{
    /**
     * @var Temporada
     */
    private $temporada;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $temporada = new Temporada();

        $episodio01 = new Episodio();
        $episodio01->assistido = true;

        $episodio02 = new Episodio();
        $episodio02->assistido = false;

        $episodio03 = new Episodio();
        $episodio03->assistido = true;

        $temporada->episodios->add($episodio01);
        $temporada->episodios->add($episodio02);
        $temporada->episodios->add($episodio03);

        $this->temporada = $temporada;
    }

    public function testBuscaPorEpisodiosAssistidos()
    {
        $episodioAssistidos = $this->temporada->getEpisodiosAssistidos();

        $this->assertCount(2, $episodioAssistidos);
        foreach ($episodioAssistidos as $episodio) {
            $this->assertTrue($episodio->assistido);
        }
    }

    public function testBuscaTodosOsEpisodios()
    {
        $episodios = $this->temporada->episodios;
        $this->assertCount(3, $episodios);
    }
}
